name: FireWings
main: FireWings\Main
version: 1.3
api: [3.0.0-ALPHA7]
author: "vk.com/eddir"
commands:
  angel:
    description: Get the fire wings
    permission: firewings.command.angel
    usage: /angel
permissions:
  firewings.command.angel:
    default: true
    description: Permission for fire wings
